env:
  browser: true
  es2020: true
extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  brace-style: off
  comma-dangle: off
  indent: [warn, 4]
  semi: off
  no-useless-constructor: off
  padded-blocks: off
  space-before-function-paren: off
  '@typescript-eslint/semi': [warn]
  '@typescript-eslint/no-useless-constructor': [warn]
